sudo: required
language: bash
services: docker

env:
 - IMAGE=ffmpeg VERSION=3.3.4 OS=alpine
 - IMAGE=ffmpeg VERSION=3.3.5 OS=alpine
 - IMAGE=ffmpeg VERSION=3.3 OS=alpine
 - IMAGE=ffmpeg VERSION=3.4 OS=alpine
 - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then IMAGE=ffmpeg VERSION=snapshot OS=alpine ; fi

before_script:
  - env | sort
  - IMAGE_VERSION="${IMAGE}:${VERSION}-${OS}"
  - LOCAL_DIR="${IMAGE}-${VERSION}-${OS}"

script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` -t $DOCKER_USERNAME/$IMAGE:latest -t $DOCKER_USERNAME/$IMAGE_VERSION $LOCAL_DIR
- docker images
- docker run $DOCKER_USERNAME/$IMAGE_VERSION -buildconf
- if [[ "$VERSION" == "3.4" ]]; docker tag $DOCKER_USERNAME/$IMAGE:latest ; fi
- docker tag $DOCKER_USERNAME/$IMAGE_VERSION
- if [[ "$VERSION" == "3.4" ]]; docker push $DOCKER_USERNAME/$IMAGE:latest ; fi
- docker push $DOCKER_USERNAME/$IMAGE_VERSION
